In [18]:
import datetime as dt
import time as t

In [19]:
t.time()

1569302943.6627557

In [10]:
d = dt.datetime.fromtimestamp(t.time())

In [11]:
d

datetime.datetime(2019, 9, 24, 10, 56, 32, 491652)

In [17]:
d.year,d.month,d.day,d.hour,d.minute,d.second

(2019, 9, 24, 10, 56, 32)

In [20]:
### Numpy:

In [21]:
import numpy as np

In [23]:
mylist = [1,2,3,4]
n = np.array(mylist)
n

array([1, 2, 3, 4])

In [24]:
m = np.array([5,6,7,8])
m

array([5, 6, 7, 8])

In [27]:
nm = np.array([(1,2,3,4),(1,2,3,4)])

In [28]:
nm

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [29]:
np.shape(nm)

(2, 4)

In [32]:
a = np.arange(0,30,2)

In [41]:
np.shape(a)

(15,)

In [44]:
a.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [69]:
a = np.linspace(0,4,9)

In [70]:
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [71]:
a.resize(3,3)
a

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [72]:
np.shape(a)

(3, 3)

In [73]:
a = np.resize(3,3)

In [74]:
a

array([3, 3, 3])

In [78]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
np.diag(nm)

array([1, 2])

In [87]:
a = np.array([1,2,3,4])

In [88]:
a

array([1, 2, 3, 4])

In [89]:
a.sum()

10

In [90]:
a.max()

4

In [91]:
a.min()

1

In [92]:
a.mean()

2.5

In [93]:
a.std()

1.118033988749895

In [97]:
a.argmax(),a.max()

(3, 4)

In [98]:
a.argmin()

0

In [105]:
a = np.arange(13)**2

In [106]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [107]:
a[0],a[2],a[1:3]

(0, 4, array([1, 4], dtype=int32))

In [108]:
a[-1]

144

In [109]:
a[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [111]:
a[::-1]

array([144, 121, 100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0],
      dtype=int32)

In [114]:
r = np.arange(36)
r.resize(6,6)

In [115]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [116]:
r[2,2]

14

In [117]:
r[3,3:6]

array([21, 22, 23])

In [118]:
r[:2,:1]

array([[0],
       [6]])

In [124]:
r1 = r[:3,:3]

In [125]:
r1

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [126]:
r1

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [127]:
r1[:] = 0

In [128]:
r1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [129]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [134]:
r_copy = r.copy()
print(r_copy)
print(r.copy())

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [135]:
r_copy[:] = 10

In [136]:
print(r_copy)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [137]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [143]:
test = np.random.randint(0,9,(4,3))

In [144]:
test

array([[7, 5, 8],
       [8, 1, 7],
       [2, 7, 4],
       [8, 3, 7]])

In [145]:
for i in test:
    print(i)

[7 5 8]
[8 1 7]
[2 7 4]
[8 3 7]


In [146]:
for i in range(len(test)):
    print(test[i])

[7 5 8]
[8 1 7]
[2 7 4]
[8 3 7]


In [148]:
for i,row in enumerate(test):
    print('row',i,'is',row)

row 0 is [7 5 8]
row 1 is [8 1 7]
row 2 is [2 7 4]
row 3 is [8 3 7]


In [150]:
test1 = test*2
test1

array([[14, 10, 16],
       [16,  2, 14],
       [ 4, 14,  8],
       [16,  6, 14]])

In [152]:
for i, j in zip(test,test1):
    print(i,' + ',j,' = ',i+j )

[7 5 8]  +  [14 10 16]  =  [21 15 24]
[8 1 7]  +  [16  2 14]  =  [24  3 21]
[2 7 4]  +  [ 4 14  8]  =  [ 6 21 12]
[8 3 7]  +  [16  6 14]  =  [24  9 21]


In [155]:
my = lambda a,b,c:a+b+c

In [156]:
my(1,2,3)

6

In [157]:
my_list = [i for i in range(1,100) if i%2 == 0]
my_list

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [167]:
class Person:
    department = "School of Python"
    def setname(self,name):
        self.name=name
    def setlocation(self,location):
        self.location=location

In [185]:
person = Person()
person.setname("Niharikaa")
person.setlocation("Jettipalem")
print('{} lives in {} and working in the department {}'.format(person.name,person.location,person.department))

Niharikaa lives in Jettipalem and working in the department School of Python


In [175]:
s = [1,2,3,4,5]
s1 = [2,3,4,5,6]

In [179]:
cheaper = map(min,s,s1)

In [180]:
print(cheaper)

In [186]:
for item in cheaper:
    print(item)

1
2
3
4
5


### Pandas:

In [189]:
import pandas as pd
pd.Series?

In [190]:
animals = ["Tiger","Monkey","Dog"]
pd.Series(animals)

0     Tiger
1    Monkey
2       Dog
dtype: object

In [192]:
numbers = [1,2,3,4]
pd.Series(numbers)

0    1
1    2
2    3
3    4
dtype: int64

In [193]:
animal = ["tiger","Dog",None]
pd.Series(animal)

0    tiger
1      Dog
2     None
dtype: object

In [194]:
num = [1,2,3,None]
pd.Series(num)

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [195]:
import numpy as np


In [196]:
np.NaN == np.NaN

False

In [197]:
np.NaN == None

False

In [204]:
np.isnan(np.nan)

True

In [209]:
sports = {"Hockey" : "India",
          "Golf" : " Japan",
          " Cricket" : "England",
          " Archery" : " China"}
a = pd.Series(sports)
a

Hockey        India
Golf          Japan
 Cricket    England
 Archery      China
dtype: object

In [210]:
a.index

Index(['Hockey', 'Golf', ' Cricket', ' Archery'], dtype='object')

In [217]:
a = pd.Series( ["India","Japan","China"],index =["Tiger","Dog","Monkey"])

In [218]:
a

Tiger     India
Dog       Japan
Monkey    China
dtype: object

In [215]:
a.index

Index(['India', 'Japan', 'China'], dtype='object')

In [219]:
sports = {"India" : "Hockey",
          "Japan" : "polo",
          "canada" : "Cricket"}
a = pd.Series(sports)

In [220]:
a

India      Hockey
Japan        polo
canada    Cricket
dtype: object

In [222]:
a.iloc[0]

'Hockey'

In [223]:
a.loc["India"]

'Hockey'

In [224]:
newsports = {99 : "India",
             100 : "Japan",
             101 : "Canada",
             102 : "Kenya"}
sports1 = pd.Series(newsports)

In [225]:
sports1

99      India
100     Japan
101    Canada
102     Kenya
dtype: object

In [228]:
sports1["India"]

KeyError: 'India'

In [230]:
a = pd.Series([99,100,101,102])
a

0     99
1    100
2    101
3    102
dtype: int64

In [231]:
a[0]

99

In [232]:
a.iloc[2]

101

In [233]:
a.loc[3]

102

In [234]:
import numpy as np
total = np.sum(a)
total

402

In [240]:
s = pd.Series(np.random.randint(0,100,10000))

In [242]:
s.head()

0    60
1    55
2    10
3    12
4     0
dtype: int32

In [243]:
len(s)

10000

In [246]:
%%timeit -n 100
summary = 0
for i in s:
    summary += i
    

1.24 ms ± 131 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [247]:
%%timeit -n 100
summary = np.sum(s)

128 µs ± 17.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [248]:
s += 2
s.head()

0    62
1    57
2    12
3    14
4     2
dtype: int32

In [249]:
a = pd.Series([1,2,3])
a

0    1
1    2
2    3
dtype: int64

In [250]:
a.loc['animals'] = "Dog"

In [251]:
a

0            1
1            2
2            3
animals    Dog
dtype: object

In [262]:
sports = pd.Series({"Hockey" : "India",
          "Golf" : " Japan",
          " Cricket" : "England",
          " Archery" : " China"})
cricket_loving_countries = pd.Series(["Australia",
                                     "kenya",
                                     "India",
                                    "America"],
                        index=["Cricket",
                              "Cricket",
                              "Cricket",
                               "Cricket"])
all_countries = sports.append(cricket_loving_countries)

In [264]:
all_countries
sports

Hockey        India
Golf          Japan
 Cricket    England
 Archery      China
dtype: object

In [265]:
import pandas as pd


In [268]:
purchase_1 = pd.Series({"name" : "Niharikaa",
                       "purchase_item" : "Dog food",
                       "price" : 20.22})
purchase_2 = pd.Series({"name" : "Srivatsav",
                       "purchase_item" : "kitty litter",
                       "price" : 30.33})
purchase_3 = pd.Series({"name" : "Prasad",
                       "purchase_item" : "cattle food",
                       "price" : 400.56})

df = pd.DataFrame([purchase_1,purchase_2,purchase_3],index = (["store-1","store-2","store-1"]))


In [269]:
df

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-2  Srivatsav  kitty litter   30.33
store-1     Prasad   cattle food  400.56

In [271]:
df.head()


name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-2  Srivatsav  kitty litter   30.33
store-1     Prasad   cattle food  400.56

In [272]:
df.iloc[2]

name                  Prasad
purchase_item    cattle food
price                 400.56
Name: store-1, dtype: object

In [276]:
type(df.loc["store-1"])

pandas.core.frame.DataFrame

In [277]:
df.loc['store-1']

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-1     Prasad   cattle food  400.56

In [278]:
df.loc['store-1','price']

store-1     20.22
store-1    400.56
Name: price, dtype: float64

In [279]:
df.T

store-1       store-2      store-1
name           Niharikaa     Srivatsav       Prasad
purchase_item   Dog food  kitty litter  cattle food
price              20.22         30.33       400.56

In [282]:
df.T.loc['price']

store-1     20.22
store-2     30.33
store-1    400.56
Name: price, dtype: object

In [283]:
df.loc["store-1"]["price"]

store-1     20.22
store-1    400.56
Name: price, dtype: float64

In [284]:
df

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-2  Srivatsav  kitty litter   30.33
store-1     Prasad   cattle food  400.56

In [292]:
df.loc[:,["name",'price']]

name   price
store-1  Niharikaa   20.22
store-2  Srivatsav   30.33
store-1     Prasad  400.56

In [293]:
df.columns

Index(['name', 'purchase_item', 'price'], dtype='object')

In [295]:
df.values

array([['Niharikaa', 'Dog food', 20.22],
       ['Srivatsav', 'kitty litter', 30.33],
       ['Prasad', 'cattle food', 400.56]], dtype=object)

In [297]:
df.drop("store-2")

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-1     Prasad   cattle food  400.56

In [298]:
df

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-2  Srivatsav  kitty litter   30.33
store-1     Prasad   cattle food  400.56

In [299]:
copy_df  = df.copy()

In [301]:
copy_df = copy_df.drop("store-1")

In [302]:
copy_df

name purchase_item  price
store-2  Srivatsav  kitty litter  30.33

In [303]:
df.copy()

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-2  Srivatsav  kitty litter   30.33
store-1     Prasad   cattle food  400.56

In [305]:
del copy_df["name"]

In [306]:
copy_df

purchase_item  price
store-2  kitty litter  30.33

In [307]:
df

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-2  Srivatsav  kitty litter   30.33
store-1     Prasad   cattle food  400.56

In [316]:
costs = df["price"]
costs

store-1     24.22
store-2     34.33
store-1    404.56
Name: price, dtype: float64

In [317]:
costs += 2
costs

store-1     26.22
store-2     36.33
store-1    406.56
Name: price, dtype: float64

In [318]:
df

name purchase_item   price
store-1  Niharikaa      Dog food   26.22
store-2  Srivatsav  kitty litter   36.33
store-1     Prasad   cattle food  406.56

NameError: name 'olympics' is not defined

In [330]:
df = pd.read_csv("olympics.csv",index_col=0,skiprows=1)
df.head()

№ Summer  01 !  02 !  03 !  Total  № Winter  01 !.1  \
Afghanistan (AFG)              13     0     0     2      2         0       0   
Algeria (ALG)                  12     5     2     8     15         3       0   
Argentina (ARG)                23    18    24    28     70        18       0   
Armenia (ARM)                   5     1     2     9     12         6       0   
Australasia (ANZ) [ANZ]         2     3     4     5     12         0       0   

                         02 !.1  03 !.1  Total.1  № Games  01 !.2  02 !.2  \
Afghanistan (AFG)             0       0        0       13       0       0   
Algeria (ALG)                 0       0        0       15       5       2   
Argentina (ARG)               0       0        0       41      18      24   
Armenia (ARM)                 0       0        0       11       1       2   
Australasia (ANZ) [ANZ]       0       0        0        2       3       4   

                         03 !.2  Combined total  
Afghanistan (AFG)             2               2  
Algeria (ALG)                 8              15  
Argentina (ARG)              28              70  
Armenia (ARM)                 9              12  
Australasia (ANZ) [ANZ]       5              12

In [331]:
df.columns

Index(['№ Summer', '01 !', '02 !', '03 !', 'Total', '№ Winter', '01 !.1',
       '02 !.1', '03 !.1', 'Total.1', '№ Games', '01 !.2', '02 !.2', '03 !.2',
       'Combined total'],
      dtype='object')

In [347]:
for col in df.columns:
    if col[:2] == "01":
        df.rename(columns={col:'Gold' + col[4:]},inplace=True)
    if col[:2] == "02":
        df.rename(columns={col:"Silver" + col[4:]},inplace=True)
    if col[:2] == "03":
        df.rename(columns={col:"Bronze" + col[4:]},inplace=True)

In [343]:
df.head()

№ Summer  Gold  Silver  Bronze  Total  № Winter  \
Afghanistan (AFG)              13     0       0       2      2         0   
Algeria (ALG)                  12     5       2       8     15         3   
Argentina (ARG)                23    18      24      28     70        18   
Armenia (ARM)                   5     1       2       9     12         6   
Australasia (ANZ) [ANZ]         2     3       4       5     12         0   

                         Gold.1  Silver.1  Bronze.1  Total.1  № Games  Gold.2  \
Afghanistan (AFG)             0         0         0        0       13       0   
Algeria (ALG)                 0         0         0        0       15       5   
Argentina (ARG)               0         0         0        0       41      18   
Armenia (ARM)                 0         0         0        0       11       1   
Australasia (ANZ) [ANZ]       0         0         0        0        2       3   

                         Silver.2  Bronze.2  Combined total  
Afghanistan (AFG)               0         2               2  
Algeria (ALG)                   2         8              15  
Argentina (ARG)                24        28              70  
Armenia (ARM)                   2         9              12  
Australasia (ANZ) [ANZ]         4         5              12

'Co'