In [18]:
import datetime as dt
import time as t

In [19]:
t.time()

1569302943.6627557

In [10]:
d = dt.datetime.fromtimestamp(t.time())

In [11]:
d

datetime.datetime(2019, 9, 24, 10, 56, 32, 491652)

In [17]:
d.year,d.month,d.day,d.hour,d.minute,d.second

(2019, 9, 24, 10, 56, 32)

In [20]:
### Numpy:

In [21]:
import numpy as np

In [23]:
mylist = [1,2,3,4]
n = np.array(mylist)
n

array([1, 2, 3, 4])

In [24]:
m = np.array([5,6,7,8])
m

array([5, 6, 7, 8])

In [27]:
nm = np.array([(1,2,3,4),(1,2,3,4)])

In [28]:
nm

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [29]:
np.shape(nm)

(2, 4)

In [32]:
a = np.arange(0,30,2)

In [41]:
np.shape(a)

(15,)

In [44]:
a.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [69]:
a = np.linspace(0,4,9)

In [70]:
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [71]:
a.resize(3,3)
a

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [72]:
np.shape(a)

(3, 3)

In [73]:
a = np.resize(3,3)

In [74]:
a

array([3, 3, 3])

In [78]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
np.diag(nm)

array([1, 2])

In [87]:
a = np.array([1,2,3,4])

In [88]:
a

array([1, 2, 3, 4])

In [89]:
a.sum()

10

In [90]:
a.max()

4

In [91]:
a.min()

1

In [92]:
a.mean()

2.5

In [93]:
a.std()

1.118033988749895

In [97]:
a.argmax(),a.max()

(3, 4)

In [98]:
a.argmin()

0

In [105]:
a = np.arange(13)**2

In [106]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [107]:
a[0],a[2],a[1:3]

(0, 4, array([1, 4], dtype=int32))

In [108]:
a[-1]

144

In [109]:
a[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [111]:
a[::-1]

array([144, 121, 100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0],
      dtype=int32)

In [114]:
r = np.arange(36)
r.resize(6,6)

In [115]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [116]:
r[2,2]

14

In [117]:
r[3,3:6]

array([21, 22, 23])

In [118]:
r[:2,:1]

array([[0],
       [6]])

In [124]:
r1 = r[:3,:3]

In [125]:
r1

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [126]:
r1

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [127]:
r1[:] = 0

In [128]:
r1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [129]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [134]:
r_copy = r.copy()
print(r_copy)
print(r.copy())

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [135]:
r_copy[:] = 10

In [136]:
print(r_copy)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [137]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [143]:
test = np.random.randint(0,9,(4,3))

In [144]:
test

array([[7, 5, 8],
       [8, 1, 7],
       [2, 7, 4],
       [8, 3, 7]])

In [145]:
for i in test:
    print(i)

[7 5 8]
[8 1 7]
[2 7 4]
[8 3 7]


In [146]:
for i in range(len(test)):
    print(test[i])

[7 5 8]
[8 1 7]
[2 7 4]
[8 3 7]


In [148]:
for i,row in enumerate(test):
    print('row',i,'is',row)

row 0 is [7 5 8]
row 1 is [8 1 7]
row 2 is [2 7 4]
row 3 is [8 3 7]


In [150]:
test1 = test*2
test1

array([[14, 10, 16],
       [16,  2, 14],
       [ 4, 14,  8],
       [16,  6, 14]])

In [152]:
for i, j in zip(test,test1):
    print(i,' + ',j,' = ',i+j )

[7 5 8]  +  [14 10 16]  =  [21 15 24]
[8 1 7]  +  [16  2 14]  =  [24  3 21]
[2 7 4]  +  [ 4 14  8]  =  [ 6 21 12]
[8 3 7]  +  [16  6 14]  =  [24  9 21]


In [155]:
my = lambda a,b,c:a+b+c

In [156]:
my(1,2,3)

6

In [157]:
my_list = [i for i in range(1,100) if i%2 == 0]
my_list

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [167]:
class Person:
    department = "School of Python"
    def setname(self,name):
        self.name=name
    def setlocation(self,location):
        self.location=location

In [185]:
person = Person()
person.setname("Niharikaa")
person.setlocation("Jettipalem")
print('{} lives in {} and working in the department {}'.format(person.name,person.location,person.department))

Niharikaa lives in Jettipalem and working in the department School of Python


In [175]:
s = [1,2,3,4,5]
s1 = [2,3,4,5,6]

In [179]:
cheaper = map(min,s,s1)

In [180]:
print(cheaper)

In [186]:
for item in cheaper:
    print(item)

1
2
3
4
5


### Pandas:

In [189]:
import pandas as pd
pd.Series?

In [190]:
animals = ["Tiger","Monkey","Dog"]
pd.Series(animals)

0     Tiger
1    Monkey
2       Dog
dtype: object

In [192]:
numbers = [1,2,3,4]
pd.Series(numbers)

0    1
1    2
2    3
3    4
dtype: int64

In [193]:
animal = ["tiger","Dog",None]
pd.Series(animal)

0    tiger
1      Dog
2     None
dtype: object

In [194]:
num = [1,2,3,None]
pd.Series(num)

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [195]:
import numpy as np


In [196]:
np.NaN == np.NaN

False

In [197]:
np.NaN == None

False

In [204]:
np.isnan(np.nan)

True

In [209]:
sports = {"Hockey" : "India",
          "Golf" : " Japan",
          " Cricket" : "England",
          " Archery" : " China"}
a = pd.Series(sports)
a

Hockey        India
Golf          Japan
 Cricket    England
 Archery      China
dtype: object

In [210]:
a.index

Index(['Hockey', 'Golf', ' Cricket', ' Archery'], dtype='object')

In [217]:
a = pd.Series( ["India","Japan","China"],index =["Tiger","Dog","Monkey"])

In [218]:
a

Tiger     India
Dog       Japan
Monkey    China
dtype: object

In [215]:
a.index

Index(['India', 'Japan', 'China'], dtype='object')

In [219]:
sports = {"India" : "Hockey",
          "Japan" : "polo",
          "canada" : "Cricket"}
a = pd.Series(sports)

In [220]:
a

India      Hockey
Japan        polo
canada    Cricket
dtype: object

In [222]:
a.iloc[0]

'Hockey'

In [223]:
a.loc["India"]

'Hockey'

In [224]:
newsports = {99 : "India",
             100 : "Japan",
             101 : "Canada",
             102 : "Kenya"}
sports1 = pd.Series(newsports)

In [225]:
sports1

99      India
100     Japan
101    Canada
102     Kenya
dtype: object

In [228]:
sports1["India"]

KeyError: 'India'

In [230]:
a = pd.Series([99,100,101,102])
a

0     99
1    100
2    101
3    102
dtype: int64

In [231]:
a[0]

99

In [232]:
a.iloc[2]

101

In [233]:
a.loc[3]

102

In [234]:
import numpy as np
total = np.sum(a)
total

402

In [240]:
s = pd.Series(np.random.randint(0,100,10000))

In [242]:
s.head()

0    60
1    55
2    10
3    12
4     0
dtype: int32

In [243]:
len(s)

10000

In [246]:
%%timeit -n 100
summary = 0
for i in s:
    summary += i
    

1.24 ms ± 131 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [247]:
%%timeit -n 100
summary = np.sum(s)

128 µs ± 17.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [248]:
s += 2
s.head()

0    62
1    57
2    12
3    14
4     2
dtype: int32

In [249]:
a = pd.Series([1,2,3])
a

0    1
1    2
2    3
dtype: int64

In [250]:
a.loc['animals'] = "Dog"

In [251]:
a

0            1
1            2
2            3
animals    Dog
dtype: object

In [262]:
sports = pd.Series({"Hockey" : "India",
          "Golf" : " Japan",
          " Cricket" : "England",
          " Archery" : " China"})
cricket_loving_countries = pd.Series(["Australia",
                                     "kenya",
                                     "India",
                                    "America"],
                        index=["Cricket",
                              "Cricket",
                              "Cricket",
                               "Cricket"])
all_countries = sports.append(cricket_loving_countries)

In [264]:
all_countries
sports

Hockey        India
Golf          Japan
 Cricket    England
 Archery      China
dtype: object

In [1]:
import pandas as pd


In [268]:
purchase_1 = pd.Series({"name" : "Niharikaa",
                       "purchase_item" : "Dog food",
                       "price" : 20.22})
purchase_2 = pd.Series({"name" : "Srivatsav",
                       "purchase_item" : "kitty litter",
                       "price" : 30.33})
purchase_3 = pd.Series({"name" : "Prasad",
                       "purchase_item" : "cattle food",
                       "price" : 400.56})

df = pd.DataFrame([purchase_1,purchase_2,purchase_3],index = (["store-1","store-2","store-1"]))


In [269]:
df

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-2  Srivatsav  kitty litter   30.33
store-1     Prasad   cattle food  400.56

In [271]:
df.head()


name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-2  Srivatsav  kitty litter   30.33
store-1     Prasad   cattle food  400.56

In [272]:
df.iloc[2]

name                  Prasad
purchase_item    cattle food
price                 400.56
Name: store-1, dtype: object

In [276]:
type(df.loc["store-1"])

pandas.core.frame.DataFrame

In [277]:
df.loc['store-1']

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-1     Prasad   cattle food  400.56

In [278]:
df.loc['store-1','price']

store-1     20.22
store-1    400.56
Name: price, dtype: float64

In [279]:
df.T

store-1       store-2      store-1
name           Niharikaa     Srivatsav       Prasad
purchase_item   Dog food  kitty litter  cattle food
price              20.22         30.33       400.56

In [282]:
df.T.loc['price']

store-1     20.22
store-2     30.33
store-1    400.56
Name: price, dtype: object

In [283]:
df.loc["store-1"]["price"]

store-1     20.22
store-1    400.56
Name: price, dtype: float64

In [284]:
df

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-2  Srivatsav  kitty litter   30.33
store-1     Prasad   cattle food  400.56

In [292]:
df.loc[:,["name",'price']]

name   price
store-1  Niharikaa   20.22
store-2  Srivatsav   30.33
store-1     Prasad  400.56

In [293]:
df.columns

Index(['name', 'purchase_item', 'price'], dtype='object')

In [295]:
df.values

array([['Niharikaa', 'Dog food', 20.22],
       ['Srivatsav', 'kitty litter', 30.33],
       ['Prasad', 'cattle food', 400.56]], dtype=object)

In [297]:
df.drop("store-2")

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-1     Prasad   cattle food  400.56

In [298]:
df

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-2  Srivatsav  kitty litter   30.33
store-1     Prasad   cattle food  400.56

In [299]:
copy_df  = df.copy()

In [301]:
copy_df = copy_df.drop("store-1")

In [302]:
copy_df

name purchase_item  price
store-2  Srivatsav  kitty litter  30.33

In [303]:
df.copy()

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-2  Srivatsav  kitty litter   30.33
store-1     Prasad   cattle food  400.56

In [305]:
del copy_df["name"]

In [306]:
copy_df

purchase_item  price
store-2  kitty litter  30.33

In [307]:
df

name purchase_item   price
store-1  Niharikaa      Dog food   20.22
store-2  Srivatsav  kitty litter   30.33
store-1     Prasad   cattle food  400.56

In [316]:
costs = df["price"]
costs

store-1     24.22
store-2     34.33
store-1    404.56
Name: price, dtype: float64

In [317]:
costs += 2
costs

store-1     26.22
store-2     36.33
store-1    406.56
Name: price, dtype: float64

In [318]:
df

name purchase_item   price
store-1  Niharikaa      Dog food   26.22
store-2  Srivatsav  kitty litter   36.33
store-1     Prasad   cattle food  406.56

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("olympics.csv",index_col=0,skiprows=1)
df.head()

№ Summer  01 !  02 !  03 !  Total  № Winter  01 !.1  \
Afghanistan (AFG)              13     0     0     2      2         0       0   
Algeria (ALG)                  12     5     2     8     15         3       0   
Argentina (ARG)                23    18    24    28     70        18       0   
Armenia (ARM)                   5     1     2     9     12         6       0   
Australasia (ANZ) [ANZ]         2     3     4     5     12         0       0   

                         02 !.1  03 !.1  Total.1  № Games  01 !.2  02 !.2  \
Afghanistan (AFG)             0       0        0       13       0       0   
Algeria (ALG)                 0       0        0       15       5       2   
Argentina (ARG)               0       0        0       41      18      24   
Armenia (ARM)                 0       0        0       11       1       2   
Australasia (ANZ) [ANZ]       0       0        0        2       3       4   

                         03 !.2  Combined total  
Afghanistan (AFG)             2               2  
Algeria (ALG)                 8              15  
Argentina (ARG)              28              70  
Armenia (ARM)                 9              12  
Australasia (ANZ) [ANZ]       5              12

In [3]:
df.columns

Index(['№ Summer', '01 !', '02 !', '03 !', 'Total', '№ Winter', '01 !.1',
       '02 !.1', '03 !.1', 'Total.1', '№ Games', '01 !.2', '02 !.2', '03 !.2',
       'Combined total'],
      dtype='object')

In [128]:
for col in df.columns:
    if col[:2] == "01":
        df.rename(columns={col:'Gold' + col[4:]},inplace=True)
    if col[:2] == "02":
        df.rename(columns={col:"Silver" + col[4:]},inplace=True)
    if col[:2] == "03":
        df.rename(columns={col:"Bronze" + col[4:]},inplace=True)
    if col[0] == "№":
        df.rename(columns={col:"#" + col[1:]},inplace=True)

In [129]:
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan         13     0       0       2      2         0       0   
Algeria             12     5       2       8     15         3       0   
Argentina           23    18      24      28     70        18       0   
Armenia              5     1       2       9     12         6       0   
Australasia          2     3       4       5     12         0       0   

              Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  \
Afghanistan          0         0        0       13       0         0   
Algeria              0         0        0       15       5         2   
Argentina            0         0        0       41      18        24   
Armenia              0         0        0       11       1         2   
Australasia          0         0        0        2       3         4   

              Bronze.2  Combined total  Ids  
Afghanistan          2               2  AFG  
Algeria              8              15  ALG  
Argentina           28              70  ARG  
Armenia              9              12  ARM  
Australasia          5              12  ANZ

In [6]:
df['Gold'] > 0

Afghanistan (AFG)                               False
Algeria (ALG)                                    True
Argentina (ARG)                                  True
Armenia (ARM)                                    True
Australasia (ANZ) [ANZ]                          True
Australia (AUS) [AUS] [Z]                        True
Austria (AUT)                                    True
Azerbaijan (AZE)                                 True
Bahamas (BAH)                                    True
Bahrain (BRN)                                   False
Barbados (BAR) [BAR]                            False
Belarus (BLR)                                    True
Belgium (BEL)                                    True
Bermuda (BER)                                   False
Bohemia (BOH) [BOH] [Z]                         False
Botswana (BOT)                                  False
Brazil (BRA)                                     True
British West Indies (BWI) [BWI]                 False
Bulgaria (BUL) [H]          

In [6]:
only_Gold = df.where(df['Gold']>0)
only_Gold.tail()

# Summer    Gold  Silver  \
Independent Olympic Participants (IOP) [IOP]       NaN     NaN     NaN   
Zambia (ZAM) [ZAM]                                 NaN     NaN     NaN   
Zimbabwe (ZIM) [ZIM]                              12.0     3.0     4.0   
Mixed team (ZZX) [ZZX]                             3.0     8.0     5.0   
Totals                                            27.0  4809.0  4775.0   

                                              Bronze    Total  # Winter  \
Independent Olympic Participants (IOP) [IOP]     NaN      NaN       NaN   
Zambia (ZAM) [ZAM]                               NaN      NaN       NaN   
Zimbabwe (ZIM) [ZIM]                             1.0      8.0       1.0   
Mixed team (ZZX) [ZZX]                           4.0     17.0       0.0   
Totals                                        5130.0  14714.0      22.0   

                                              Gold.1  Silver.1  Bronze.1  \
Independent Olympic Participants (IOP) [IOP]     NaN       NaN       NaN   
Zambia (ZAM) [ZAM]                               NaN       NaN       NaN   
Zimbabwe (ZIM) [ZIM]                             0.0       0.0       0.0   
Mixed team (ZZX) [ZZX]                           0.0       0.0       0.0   
Totals                                         959.0     958.0     948.0   

                                              Total.1  # Games  Gold.2  \
Independent Olympic Participants (IOP) [IOP]      NaN      NaN     NaN   
Zambia (ZAM) [ZAM]                                NaN      NaN     NaN   
Zimbabwe (ZIM) [ZIM]                              0.0     13.0     3.0   
Mixed team (ZZX) [ZZX]                            0.0      3.0     8.0   
Totals                                         2865.0     49.0  5768.0   

                                              Silver.2  Bronze.2  \
Independent Olympic Participants (IOP) [IOP]       NaN       NaN   
Zambia (ZAM) [ZAM]                                 NaN       NaN   
Zimbabwe (ZIM) [ZIM]                               4.0       1.0   
Mixed team (ZZX) [ZZX]                             5.0       4.0   
Totals                                          5733.0    6078.0   

                                              Combined total  
Independent Olympic Participants (IOP) [IOP]             NaN  
Zambia (ZAM) [ZAM]                                       NaN  
Zimbabwe (ZIM) [ZIM]                                     8.0  
Mixed team (ZZX) [ZZX]                                  17.0  
Totals                                               17579.0

In [7]:
only_Gold = only_Gold.dropna()
only_Gold.tail()
only_Gold["Gold"].count()

100

In [8]:
df["Gold"].count()

147

In [15]:
df.where(df["Silver"]>0).count()

# Summer          125
Gold              125
Silver            125
Bronze            125
Total             125
# Winter          125
Gold.1            125
Silver.1          125
Bronze.1          125
Total.1           125
# Games           125
Gold.2            125
Silver.2          125
Bronze.2          125
Combined total    125
dtype: int64

In [18]:
df["Bronze"].count()

147

In [11]:
a = df.where(df["Gold"]>30)

In [13]:
a.head()
a.dropna()

# Summer    Gold  Silver  Bronze  \
Australia (AUS) [AUS] [Z]                25.0   139.0   152.0   177.0   
Belgium (BEL)                            25.0    37.0    52.0    53.0   
Bulgaria (BUL) [H]                       19.0    51.0    85.0    78.0   
Canada (CAN)                             25.0    59.0    99.0   121.0   
China (CHN) [CHN]                         9.0   201.0   146.0   126.0   
Cuba (CUB) [Z]                           19.0    72.0    67.0    70.0   
Czechoslovakia (TCH) [TCH]               16.0    49.0    49.0    45.0   
Denmark (DEN) [Z]                        26.0    43.0    68.0    68.0   
Finland (FIN)                            24.0   101.0    84.0   117.0   
France (FRA) [O] [P] [Z]                 27.0   202.0   223.0   246.0   
Germany (GER) [GER] [Z]                  15.0   174.0   182.0   217.0   
East Germany (GDR) [GDR]                  5.0   153.0   129.0   127.0   
West Germany (FRG) [FRG]                  5.0    56.0    67.0    81.0   
Great Britain (GBR) [GBR] [Z]            27.0   236.0   272.0   272.0   
Hungary (HUN)                            25.0   167.0   144.0   165.0   
Italy (ITA) [M] [S]                      26.0   198.0   166.0   185.0   
Japan (JPN)                              21.0   130.0   126.0   142.0   
South Korea (KOR)                        16.0    81.0    82.0    80.0   
Netherlands (NED) [Z]                    25.0    77.0    85.0   104.0   
New Zealand (NZL) [NZL]                  22.0    42.0    18.0    39.0   
Norway (NOR) [Q]                         24.0    56.0    49.0    43.0   
Poland (POL)                             20.0    64.0    82.0   125.0   
Romania (ROU)                            20.0    88.0    94.0   119.0   
Russia (RUS) [RUS]                        5.0   132.0   121.0   142.0   
Soviet Union (URS) [URS]                  9.0   395.0   319.0   296.0   
Unified Team (EUN) [EUN]                  1.0    45.0    38.0    29.0   
Spain (ESP) [Z]                          22.0    37.0    59.0    35.0   
Sweden (SWE) [Z]                         26.0   143.0   164.0   176.0   
Switzerland (SUI)                        27.0    47.0    73.0    65.0   
Turkey (TUR)                             21.0    39.0    25.0    24.0   
Ukraine (UKR)                             5.0    33.0    27.0    55.0   
United States (USA) [P] [Q] [R] [Z]      26.0   976.0   757.0   666.0   
Totals                                   27.0  4809.0  4775.0  5130.0   

                                       Total  # Winter  Gold.1  Silver.1  \
Australia (AUS) [AUS] [Z]              468.0      18.0     5.0       3.0   
Belgium (BEL)                          142.0      20.0     1.0       1.0   
Bulgaria (BUL) [H]                     214.0      19.0     1.0       2.0   
Canada (CAN)                           279.0      22.0    62.0      56.0   
China (CHN) [CHN]                      473.0      10.0    12.0      22.0   
Cuba (CUB) [Z]                         209.0       0.0     0.0       0.0   
Czechoslovakia (TCH) [TCH]             143.0      16.0     2.0       8.0   
Denmark (DEN) [Z]                      179.0      13.0     0.0       1.0   
Finland (FIN)                          302.0      22.0    42.0      62.0   
France (FRA) [O] [P] [Z]               671.0      22.0    31.0      31.0   
Germany (GER) [GER] [Z]                573.0      11.0    78.0      78.0   
East Germany (GDR) [GDR]               409.0       6.0    39.0      36.0   
West Germany (FRG) [FRG]               204.0       6.0    11.0      15.0   
Great Britain (GBR) [GBR] [Z]          780.0      22.0    10.0       4.0   
Hungary (HUN)                          476.0      22.0     0.0       2.0   
Italy (ITA) [M] [S]                    549.0      22.0    37.0      34.0   
Japan (JPN)                            398.0      20.0    10.0      17.0   
South Korea (KOR)                      243.0      17.0    26.0      17.0   
Netherlands (NED) [Z]                  266.0      20.0    37.0      38.0   
New Zealand (NZL) [NZL]           

In [14]:
len(df['Gold'])

147

In [20]:
len(df[(df["Gold.1"]>0) | (df["Gold"] >0)])

101

In [23]:
 df["Country"] = df.index
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  \
Afghanistan (AFG)              13     0       0       2      2         0   
Algeria (ALG)                  12     5       2       8     15         3   
Argentina (ARG)                23    18      24      28     70        18   
Armenia (ARM)                   5     1       2       9     12         6   
Australasia (ANZ) [ANZ]         2     3       4       5     12         0   

                         Gold.1  Silver.1  Bronze.1  Total.1  # Games  Gold.2  \
Afghanistan (AFG)             0         0         0        0       13       0   
Algeria (ALG)                 0         0         0        0       15       5   
Argentina (ARG)               0         0         0        0       41      18   
Armenia (ARM)                 0         0         0        0       11       1   
Australasia (ANZ) [ANZ]       0         0         0        0        2       3   

                         Silver.2  Bronze.2  Combined total  \
Afghanistan (AFG)               0         2               2   
Algeria (ALG)                   2         8              15   
Argentina (ARG)                24        28              70   
Armenia (ARM)                   2         9              12   
Australasia (ANZ) [ANZ]         4         5              12   

                                         Country  
Afghanistan (AFG)              Afghanistan (AFG)  
Algeria (ALG)                      Algeria (ALG)  
Argentina (ARG)                  Argentina (ARG)  
Armenia (ARM)                      Armenia (ARM)  
Australasia (ANZ) [ANZ]  Australasia (ANZ) [ANZ]

In [24]:
df = df.set_index("Gold")
df.head()

# Summer  Silver  Bronze  Total  # Winter  Gold.1  Silver.1  Bronze.1  \
Gold                                                                          
0           13       0       2      2         0       0         0         0   
5           12       2       8     15         3       0         0         0   
18          23      24      28     70        18       0         0         0   
1            5       2       9     12         6       0         0         0   
3            2       4       5     12         0       0         0         0   

      Total.1  # Games  Gold.2  Silver.2  Bronze.2  Combined total  \
Gold                                                                 
0           0       13       0         0         2               2   
5           0       15       5         2         8              15   
18          0       41      18        24        28              70   
1           0       11       1         2         9              12   
3           0        2       3         4         5              12   

                      Country  
Gold                           
0           Afghanistan (AFG)  
5               Algeria (ALG)  
18            Argentina (ARG)  
1               Armenia (ARM)  
3     Australasia (ANZ) [ANZ]

In [25]:
df = df.reset_index()

In [27]:
df = df.set_index("Country")

In [28]:
df

Gold  # Summer  Silver  Bronze  \
Country                                                                        
Afghanistan (AFG)                                0        13       0       2   
Algeria (ALG)                                    5        12       2       8   
Argentina (ARG)                                 18        23      24      28   
Armenia (ARM)                                    1         5       2       9   
Australasia (ANZ) [ANZ]                          3         2       4       5   
Australia (AUS) [AUS] [Z]                      139        25     152     177   
Austria (AUT)                                   18        26      33      35   
Azerbaijan (AZE)                                 6         5       5      15   
Bahamas (BAH)                                    5        15       2       5   
Bahrain (BRN)                                    0         8       0       1   
Barbados (BAR) [BAR]                             0        11       0       1   
Belarus (BLR)                                   12         5      24      39   
Belgium (BEL)                                   37        25      52      53   
Bermuda (BER)                                    0        17       0       1   
Bohemia (BOH) [BOH] [Z]                          0         3       1       3   
Botswana (BOT)                                   0         9       1       0   
Brazil (BRA)                                    23        21      30      55   
British West Indies (BWI) [BWI]                  0         1       0       2   
Bulgaria (BUL) [H]                              51        19      85      78   
Burundi (BDI)                                    1         5       0       0   
Cameroon (CMR)                                   3        13       1       1   
Canada (CAN)                                    59        25      99     121   
Chile (CHI) [I]                                  2        22       7       4   
China (CHN) [CHN]                              201         9     146     126   
Colombia (COL)                                   2        18       6      11   
Costa Rica (CRC)                                 1        14       1       2   
Ivory Coast (CIV) [CIV]                          0        12       1       0   
Croatia (CRO)                                    6         6       7      10   
Cuba (CUB) [Z]                                  72        19      67      70   
Cyprus (CYP)                                     0         9       1       0   
...                                            ...       ...     ...     ...   
Sri Lanka (SRI) [SRI]                            0        16       2       0   
Sudan (SUD)                                      0        11       1       0   
Suriname (SUR) [E]                               1        11       0       1   
Sweden (SWE) [Z]                               143        26     164     176   
Switzerland (SUI)                               47        27      73      65   
Syria (SYR)                                      1        12       1       1   
Chinese Taipei (TPE) [TPE] [TPE2]                2        13       7      12   
Tajikistan (TJK)                                 0         5       1       2   
Tanzania (TAN) [TAN]                             0        12       2       0   
Thailand (THA)                                   7        15       6      11   
Togo (TOG)                                       0         9       0       1   
Tonga (TGA)                                      0         8       1       0   
Trinidad and Tobago (TRI) [TRI]                  2        16       5      11   
Tunisia (TUN)                                    3        13       3       4   
Turkey (TUR)                                    39        21      25      24   
Uganda (UGA)                                     2        14       3       2   
Ukraine (UKR)                                   33         5      27      55   
United Arab Emirates (UAE)                    

In [67]:
data = pd.read_csv("census.csv")
data.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  ...  RDOMESTICMIG2011  \
0        4779736            4780127          4785161  ...          0.002295   
1          54571              54571            54660  ...          7.242091   
2         182265             182265           183193  ...         14.832960   
3          27457              27457            27341  ...         -4.728132   
4          22915              22919            22861  ...         -5.527043   

   RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  RDOMESTICMIG2015  \
0         -0.193196          0.381066          0.582002         -0.467369   
1         -2.915927         -3.012349          2.265971         -2.530799   
2         17.647293         21.845705         19.243287         17.197872   
3         -2.500690         -7.056824         -3.904217        -10.543299   
4         -5.068871         -6.201001         -0.177537          0.177258   

   RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015  
0     1.030015     0.826644     1.383282     1.724718     0.712594  
1     7.606016    -2.626146    -2.722002     2.592270    -2.187333  
2    15.844176    18.559627    22.727626    20.317142    18.293499  
3    -4.874741    -2.758113    -7.167664    -3.978583   -10.543299  
4    -5.088389    -4.363636    -5.403729     0.754533     1.107861  

[5 rows x 100 columns]

In [40]:
data["SUMLEV"].unique()

array([40, 50], dtype=int64)

In [37]:
data = data[data["SUMLEV"] ==50]
data.head()

Empty DataFrame
Columns: [SUMLEV, REGION, DIVISION, STATE, COUNTY, STNAME, CTYNAME, CENSUS2010POP, ESTIMATESBASE2010, POPESTIMATE2010, POPESTIMATE2011, POPESTIMATE2012, POPESTIMATE2013, POPESTIMATE2014, POPESTIMATE2015, NPOPCHG_2010, NPOPCHG_2011, NPOPCHG_2012, NPOPCHG_2013, NPOPCHG_2014, NPOPCHG_2015, BIRTHS2010, BIRTHS2011, BIRTHS2012, BIRTHS2013, BIRTHS2014, BIRTHS2015, DEATHS2010, DEATHS2011, DEATHS2012, DEATHS2013, DEATHS2014, DEATHS2015, NATURALINC2010, NATURALINC2011, NATURALINC2012, NATURALINC2013, NATURALINC2014, NATURALINC2015, INTERNATIONALMIG2010, INTERNATIONALMIG2011, INTERNATIONALMIG2012, INTERNATIONALMIG2013, INTERNATIONALMIG2014, INTERNATIONALMIG2015, DOMESTICMIG2010, DOMESTICMIG2011, DOMESTICMIG2012, DOMESTICMIG2013, DOMESTICMIG2014, DOMESTICMIG2015, NETMIG2010, NETMIG2011, NETMIG2012, NETMIG2013, NETMIG2014, NETMIG2015, RESIDUAL2010, RESIDUAL2011, RESIDUAL2012, RESIDUAL2013, RESIDUAL2014, RESIDUAL2015, GQESTIMATESBASE2010, GQESTIMATES2010, GQESTIMATES2011, GQESTIMATES2012, GQESTIMATES2013, GQESTIMATES2014, GQESTIMATES2015, RBIRTH2011, RBIRTH2012, RBIRTH2013, RBIRTH2014, RBIRTH2015, RDEATH2011, RDEATH2012, RDEATH2013, RDEATH2014, RDEATH2015, RNATURALINC2011, RNATURALINC2012, RNATURALINC2013, RNATURALINC2014, RNATURALINC2015, RINTERNATIONALMIG2011, RINTERNATIONALMIG2012, RINTERNATIONALMIG2013, RINTERNATIONALMIG2014, RINTERNATIONALMIG2015, RDOMESTICMIG2011, RDOMESTICMIG2012, RDOMESTICMIG2013, RDOMESTICMIG2014, RDOMESTICMIG2015, RNETMIG2011, RNETMIG2012, RNETMIG2013, RNETMIG2014, RNETMIG2015]
Index: []

[0 rows x 100 columns]

In [43]:
data = data[data["SUMLEV"] ==50]

In [64]:
data.head()

CTYNAME  BIRTHS2010  BIRTHS2011  BIRTHS2012  BIRTHS2013  \
STNAME                                                                    
Alabama  Autauga County         151         636         615         574   
Alabama  Baldwin County         517        2187        2092        2160   
Alabama  Barbour County          70         335         300         283   
Alabama     Bibb County          44         266         245         259   
Alabama   Blount County         183         744         710         646   

         BIRTHS2014  BIRTHS2015  POPESTIMATE2010  POPESTIMATE2011  \
STNAME                                                              
Alabama         623         600            54660            55253   
Alabama        2186        2240           183193           186659   
Alabama         260         269            27341            27226   
Alabama         247         253            22861            22733   
Alabama         618         603            57373            57711   

         POPESTIMATE2012  POPESTIMATE2013  POPESTIMATE2014  POPESTIMATE2015  
STNAME                                                                       
Alabama            55175            55038            55290            55347  
Alabama           190396           195126           199713           203709  
Alabama            27159            26973            26815            26489  
Alabama            22642            22512            22549            22583  
Alabama            57776            57734            57658            57673

In [68]:
columns_to_be = ["STNAME",
                "CTYNAME",
                "BIRTHS2010",
                "BIRTHS2011",
                "BIRTHS2012",
                "BIRTHS2013",
                "BIRTHS2014",
                "BIRTHS2015",
                "POPESTIMATE2010",
                "POPESTIMATE2011",
                "POPESTIMATE2012",
                "POPESTIMATE2013",
                "POPESTIMATE2014",
                "POPESTIMATE2015"]
data =data[columns_to_be]

In [69]:
data.columns

Index(['STNAME', 'CTYNAME', 'BIRTHS2010', 'BIRTHS2011', 'BIRTHS2012',
       'BIRTHS2013', 'BIRTHS2014', 'BIRTHS2015', 'POPESTIMATE2010',
       'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013',
       'POPESTIMATE2014', 'POPESTIMATE2015'],
      dtype='object')

In [70]:
data.head()

STNAME         CTYNAME  BIRTHS2010  BIRTHS2011  BIRTHS2012  BIRTHS2013  \
0  Alabama         Alabama       14226       59689       59062       57938   
1  Alabama  Autauga County         151         636         615         574   
2  Alabama  Baldwin County         517        2187        2092        2160   
3  Alabama  Barbour County          70         335         300         283   
4  Alabama     Bibb County          44         266         245         259   

   BIRTHS2014  BIRTHS2015  POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  \
0       58334       58305          4785161          4801108          4816089   
1         623         600            54660            55253            55175   
2        2186        2240           183193           186659           190396   
3         260         269            27341            27226            27159   
4         247         253            22861            22733            22642   

   POPESTIMATE2013  POPESTIMATE2014  POPESTIMATE2015  
0          4830533          4846411          4858979  
1            55038            55290            55347  
2           195126           199713           203709  
3            26973            26815            26489  
4            22512            22549            22583

In [71]:
data = data.set_index(['STNAME','CTYNAME'])

In [72]:
data.head()

BIRTHS2010  BIRTHS2011  BIRTHS2012  BIRTHS2013  \
STNAME  CTYNAME                                                          
Alabama Alabama              14226       59689       59062       57938   
        Autauga County         151         636         615         574   
        Baldwin County         517        2187        2092        2160   
        Barbour County          70         335         300         283   
        Bibb County             44         266         245         259   

                        BIRTHS2014  BIRTHS2015  POPESTIMATE2010  \
STNAME  CTYNAME                                                   
Alabama Alabama              58334       58305          4785161   
        Autauga County         623         600            54660   
        Baldwin County        2186        2240           183193   
        Barbour County         260         269            27341   
        Bibb County            247         253            22861   

                        POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  \
STNAME  CTYNAME                                                             
Alabama Alabama                 4801108          4816089          4830533   
        Autauga County            55253            55175            55038   
        Baldwin County           186659           190396           195126   
        Barbour County            27226            27159            26973   
        Bibb County               22733            22642            22512   

                        POPESTIMATE2014  POPESTIMATE2015  
STNAME  CTYNAME                                           
Alabama Alabama                 4846411          4858979  
        Autauga County            55290            55347  
        Baldwin County           199713           203709  
        Barbour County            26815            26489  
        Bibb County               22549            22583

In [74]:
data.loc["Alabama","Autauga County"]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  """Entry point for launching an IPython kernel.


BIRTHS2010  BIRTHS2011  BIRTHS2012  BIRTHS2013  \
STNAME  CTYNAME                                                          
Alabama Autauga County         151         636         615         574   

                        BIRTHS2014  BIRTHS2015  POPESTIMATE2010  \
STNAME  CTYNAME                                                   
Alabama Autauga County         623         600            54660   

                        POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  \
STNAME  CTYNAME                                                             
Alabama Autauga County            55253            55175            55038   

                        POPESTIMATE2014  POPESTIMATE2015  
STNAME  CTYNAME                                           
Alabama Autauga County            55290            55347

In [82]:
data.loc[[("Alabama","Autauga County"),("Alabama","Barbour County")]]

BIRTHS2010  BIRTHS2011  BIRTHS2012  BIRTHS2013  \
STNAME  CTYNAME                                                          
Alabama Autauga County         151         636         615         574   
        Barbour County          70         335         300         283   

                        BIRTHS2014  BIRTHS2015  POPESTIMATE2010  \
STNAME  CTYNAME                                                   
Alabama Autauga County         623         600            54660   
        Barbour County         260         269            27341   

                        POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  \
STNAME  CTYNAME                                                             
Alabama Autauga County            55253            55175            55038   
        Barbour County            27226            27159            26973   

                        POPESTIMATE2014  POPESTIMATE2015  
STNAME  CTYNAME                                           
Alabama Autauga County            55290            55347  
        Barbour County            26815            26489

In [93]:
df1 = pd.read_csv("log.csv")
df1

time    user          video  playback position paused  volume
0   1469974424  cheryl     intro.html                  5  False    10.0
1   1469974454  cheryl     intro.html                  6    NaN     NaN
2   1469974544  cheryl     intro.html                  9    NaN     NaN
3   1469974574  cheryl     intro.html                 10    NaN     NaN
4   1469977514     bob     intro.html                  1    NaN     NaN
5   1469977544     bob     intro.html                  1    NaN     NaN
6   1469977574     bob     intro.html                  1    NaN     NaN
7   1469977604     bob     intro.html                  1    NaN     NaN
8   1469974604  cheryl     intro.html                 11    NaN     NaN
9   1469974694  cheryl     intro.html                 14    NaN     NaN
10  1469974724  cheryl     intro.html                 15    NaN     NaN
11  1469974454     sue  advanced.html                 24    NaN     NaN
12  1469974524     sue  advanced.html                 25    NaN     NaN
13  1469974424     sue  advanced.html                 23  False    10.0
14  1469974554     sue  advanced.html                 26    NaN     NaN
15  1469974624     sue  advanced.html                 27    NaN     NaN
16  1469974654     sue  advanced.html                 28    NaN     5.0
17  1469974724     sue  advanced.html                 29    NaN     NaN
18  1469974484  cheryl     intro.html                  7    NaN     NaN
19  1469974514  cheryl     intro.html                  8    NaN     NaN
20  1469974754     sue  advanced.html                 30    NaN     NaN
21  1469974824     sue  advanced.html                 31    NaN     NaN
22  1469974854     sue  advanced.html                 32    NaN     NaN
23  1469974924     sue  advanced.html                 33    NaN     NaN
24  1469977424     bob     intro.html                  1   True    10.0
25  1469977454     bob     intro.html                  1    NaN     NaN
26  1469977484     bob     intro.html                  1    NaN     NaN
27  1469977634     bob     intro.html                  1    NaN     NaN
28  1469977664     bob     intro.html                  1    NaN     NaN
29  1469974634  cheryl     intro.html                 12    NaN     NaN
30  1469974664  cheryl     intro.html                 13    NaN     NaN
31  1469977694     bob     intro.html                  1    NaN     NaN
32  1469977724     bob     intro.html                  1    NaN     NaN

In [94]:
df1.fillna

<bound method DataFrame.fillna of           time    user          video  playback position paused  volume
0   1469974424  cheryl     intro.html                  5  False    10.0
1   1469974454  cheryl     intro.html                  6    NaN     NaN
2   1469974544  cheryl     intro.html                  9    NaN     NaN
3   1469974574  cheryl     intro.html                 10    NaN     NaN
4   1469977514     bob     intro.html                  1    NaN     NaN
5   1469977544     bob     intro.html                  1    NaN     NaN
6   1469977574     bob     intro.html                  1    NaN     NaN
7   1469977604     bob     intro.html                  1    NaN     NaN
8   1469974604  cheryl     intro.html                 11    NaN     NaN
9   1469974694  cheryl     intro.html                 14    NaN     NaN
10  1469974724  cheryl     intro.html                 15    NaN     NaN
11  1469974454     sue  advanced.html                 24    NaN     NaN
12  1469974524     sue  advanc

In [95]:
df1 = df1.set_index("time")
df1 = df1.sort_index()
df1


user          video  playback position paused  volume
time                                                               
1469974424  cheryl     intro.html                  5  False    10.0
1469974424     sue  advanced.html                 23  False    10.0
1469974454  cheryl     intro.html                  6    NaN     NaN
1469974454     sue  advanced.html                 24    NaN     NaN
1469974484  cheryl     intro.html                  7    NaN     NaN
1469974514  cheryl     intro.html                  8    NaN     NaN
1469974524     sue  advanced.html                 25    NaN     NaN
1469974544  cheryl     intro.html                  9    NaN     NaN
1469974554     sue  advanced.html                 26    NaN     NaN
1469974574  cheryl     intro.html                 10    NaN     NaN
1469974604  cheryl     intro.html                 11    NaN     NaN
1469974624     sue  advanced.html                 27    NaN     NaN
1469974634  cheryl     intro.html                 12    NaN     NaN
1469974654     sue  advanced.html                 28    NaN     5.0
1469974664  cheryl     intro.html                 13    NaN     NaN
1469974694  cheryl     intro.html                 14    NaN     NaN
1469974724  cheryl     intro.html                 15    NaN     NaN
1469974724     sue  advanced.html                 29    NaN     NaN
1469974754     sue  advanced.html                 30    NaN     NaN
1469974824     sue  advanced.html                 31    NaN     NaN
1469974854     sue  advanced.html                 32    NaN     NaN
1469974924     sue  advanced.html                 33    NaN     NaN
1469977424     bob     intro.html                  1   True    10.0
1469977454     bob     intro.html                  1    NaN     NaN
1469977484     bob     intro.html                  1    NaN     NaN
1469977514     bob     intro.html                  1    NaN     NaN
1469977544     bob     intro.html                  1    NaN     NaN
1469977574     bob     intro.html                  1    NaN     NaN
1469977604     bob     intro.html                  1    NaN     NaN
1469977634     bob     intro.html                  1    NaN     NaN
1469977664     bob     intro.html                  1    NaN     NaN
1469977694     bob     intro.html                  1    NaN     NaN
1469977724     bob     intro.html                  1    NaN     NaN

In [96]:
df1.fillna(method = "bfill")

user          video  playback position paused  volume
time                                                               
1469974424  cheryl     intro.html                  5  False    10.0
1469974424     sue  advanced.html                 23  False    10.0
1469974454  cheryl     intro.html                  6   True     5.0
1469974454     sue  advanced.html                 24   True     5.0
1469974484  cheryl     intro.html                  7   True     5.0
1469974514  cheryl     intro.html                  8   True     5.0
1469974524     sue  advanced.html                 25   True     5.0
1469974544  cheryl     intro.html                  9   True     5.0
1469974554     sue  advanced.html                 26   True     5.0
1469974574  cheryl     intro.html                 10   True     5.0
1469974604  cheryl     intro.html                 11   True     5.0
1469974624     sue  advanced.html                 27   True     5.0
1469974634  cheryl     intro.html                 12   True     5.0
1469974654     sue  advanced.html                 28   True     5.0
1469974664  cheryl     intro.html                 13   True    10.0
1469974694  cheryl     intro.html                 14   True    10.0
1469974724  cheryl     intro.html                 15   True    10.0
1469974724     sue  advanced.html                 29   True    10.0
1469974754     sue  advanced.html                 30   True    10.0
1469974824     sue  advanced.html                 31   True    10.0
1469974854     sue  advanced.html                 32   True    10.0
1469974924     sue  advanced.html                 33   True    10.0
1469977424     bob     intro.html                  1   True    10.0
1469977454     bob     intro.html                  1    NaN     NaN
1469977484     bob     intro.html                  1    NaN     NaN
1469977514     bob     intro.html                  1    NaN     NaN
1469977544     bob     intro.html                  1    NaN     NaN
1469977574     bob     intro.html                  1    NaN     NaN
1469977604     bob     intro.html                  1    NaN     NaN
1469977634     bob     intro.html                  1    NaN     NaN
1469977664     bob     intro.html                  1    NaN     NaN
1469977694     bob     intro.html                  1    NaN     NaN
1469977724     bob     intro.html                  1    NaN     NaN

In [101]:
df = pd.read_csv("olympics.csv",index_col = 0,skiprows = 1)

In [102]:
df.head()

№ Summer  01 !  02 !  03 !  Total  № Winter  01 !.1  \
Afghanistan (AFG)              13     0     0     2      2         0       0   
Algeria (ALG)                  12     5     2     8     15         3       0   
Argentina (ARG)                23    18    24    28     70        18       0   
Armenia (ARM)                   5     1     2     9     12         6       0   
Australasia (ANZ) [ANZ]         2     3     4     5     12         0       0   

                         02 !.1  03 !.1  Total.1  № Games  01 !.2  02 !.2  \
Afghanistan (AFG)             0       0        0       13       0       0   
Algeria (ALG)                 0       0        0       15       5       2   
Argentina (ARG)               0       0        0       41      18      24   
Armenia (ARM)                 0       0        0       11       1       2   
Australasia (ANZ) [ANZ]       0       0        0        2       3       4   

                         03 !.2  Combined total  
Afghanistan (AFG)             2               2  
Algeria (ALG)                 8              15  
Argentina (ARG)              28              70  
Armenia (ARM)                 9              12  
Australasia (ANZ) [ANZ]       5              12

In [111]:
nameids = df.index.str.split("(")

In [113]:
df.index = nameids.str[0]

In [123]:
df.tail()

№ Summer  01 !  02 !  03 !  Total  \
Independent Olympic Participants          1     0     1     2      3   
Zambia                                   12     0     1     1      2   
Zimbabwe                                 12     3     4     1      8   
Mixed team                                3     8     5     4     17   
Totals                                   27  4809  4775  5130  14714   

                                   № Winter  01 !.1  02 !.1  03 !.1  Total.1  \
Independent Olympic Participants          0       0       0       0        0   
Zambia                                    0       0       0       0        0   
Zimbabwe                                  1       0       0       0        0   
Mixed team                                0       0       0       0        0   
Totals                                   22     959     958     948     2865   

                                   № Games  01 !.2  02 !.2  03 !.2  \
Independent Olympic Participants         1       0       1       2   
Zambia                                  12       0       1       1   
Zimbabwe                                13       3       4       1   
Mixed team                               3       8       5       4   
Totals                                  49    5768    5733    6078   

                                   Combined total  Ids  
Independent Olympic Participants                3  IOP  
Zambia                                          2  ZAM  
Zimbabwe                                        8  ZIM  
Mixed team                                     17  ZZX  
Totals                                      17579  NaN

In [121]:
df['Ids'] = nameids.str[1].str[:3]

In [122]:
df

№ Summer  01 !  02 !  03 !  Total  \
Afghanistan                              13     0     0     2      2   
Algeria                                  12     5     2     8     15   
Argentina                                23    18    24    28     70   
Armenia                                   5     1     2     9     12   
Australasia                               2     3     4     5     12   
Australia                                25   139   152   177    468   
Austria                                  26    18    33    35     86   
Azerbaijan                                5     6     5    15     26   
Bahamas                                  15     5     2     5     12   
Bahrain                                   8     0     0     1      1   
Barbados                                 11     0     0     1      1   
Belarus                                   5    12    24    39     75   
Belgium                                  25    37    52    53    142   
Bermuda                                  17     0     0     1      1   
Bohemia                                   3     0     1     3      4   
Botswana                                  9     0     1     0      1   
Brazil                                   21    23    30    55    108   
British West Indies                       1     0     0     2      2   
Bulgaria                                 19    51    85    78    214   
Burundi                                   5     1     0     0      1   
Cameroon                                 13     3     1     1      5   
Canada                                   25    59    99   121    279   
Chile                                    22     2     7     4     13   
China                                     9   201   146   126    473   
Colombia                                 18     2     6    11     19   
Costa Rica                               14     1     1     2      4   
Ivory Coast                              12     0     1     0      1   
Croatia                                   6     6     7    10     23   
Cuba                                     19    72    67    70    209   
Cyprus                                    9     0     1     0      1   
...                                     ...   ...   ...   ...    ...   
Sri Lanka                                16     0     2     0      2   
Sudan                                    11     0     1     0      1   
Suriname                                 11     1     0     1      2   
Sweden                                   26   143   164   176    483   
Switzerland                              27    47    73    65    185   
Syria                                    12     1     1     1      3   
Chinese Taipei                           13     2     7    12     21   
Tajikistan                                5     0     1     2      3   
Tanzania                                 12     0     2     0      2   
Thailand                                 15     7     6    11     24   
Togo                                      9     0     0     1      1   
Tonga                                     8     0     1     0      1   
Trinidad and Tobago                      16     2     5    11     18   
Tunisia                                  13     3     3     4     10   
Turkey                                   21    39    25    24     88   
Uganda                                   14     2     3     2      7   
Ukraine                                   5    33    27    55    115   
United Arab Emirates                      8     1     0     0      1   
United States                            26   976   757   666   2399   
Uruguay                                  20     2     2     6     10   
Uzbekistan                                5     5     5    10     20   
Venezuela                                17     2     2     8     12   
Vietnam                                  14     0     2     0      2   
Virgin Islands                           11     0     1     0      1   
Yug

In [125]:
df.tail()

№ Summer  01 !  02 !  03 !  Total  \
Independent Olympic Participants          1     0     1     2      3   
Zambia                                   12     0     1     1      2   
Zimbabwe                                 12     3     4     1      8   
Mixed team                                3     8     5     4     17   
Totals                                   27  4809  4775  5130  14714   

                                   № Winter  01 !.1  02 !.1  03 !.1  Total.1  \
Independent Olympic Participants          0       0       0       0        0   
Zambia                                    0       0       0       0        0   
Zimbabwe                                  1       0       0       0        0   
Mixed team                                0       0       0       0        0   
Totals                                   22     959     958     948     2865   

                                   № Games  01 !.2  02 !.2  03 !.2  \
Independent Olympic Participants         1       0       1       2   
Zambia                                  12       0       1       1   
Zimbabwe                                13       3       4       1   
Mixed team                               3       8       5       4   
Totals                                  49    5768    5733    6078   

                                   Combined total  Ids  
Independent Olympic Participants                3  IOP  
Zambia                                          2  ZAM  
Zimbabwe                                        8  ZIM  
Mixed team                                     17  ZZX  
Totals                                      17579  NaN

In [126]:
df.drop("Totals")

№ Summer  01 !  02 !  03 !  Total  \
Afghanistan                              13     0     0     2      2   
Algeria                                  12     5     2     8     15   
Argentina                                23    18    24    28     70   
Armenia                                   5     1     2     9     12   
Australasia                               2     3     4     5     12   
Australia                                25   139   152   177    468   
Austria                                  26    18    33    35     86   
Azerbaijan                                5     6     5    15     26   
Bahamas                                  15     5     2     5     12   
Bahrain                                   8     0     0     1      1   
Barbados                                 11     0     0     1      1   
Belarus                                   5    12    24    39     75   
Belgium                                  25    37    52    53    142   
Bermuda                                  17     0     0     1      1   
Bohemia                                   3     0     1     3      4   
Botswana                                  9     0     1     0      1   
Brazil                                   21    23    30    55    108   
British West Indies                       1     0     0     2      2   
Bulgaria                                 19    51    85    78    214   
Burundi                                   5     1     0     0      1   
Cameroon                                 13     3     1     1      5   
Canada                                   25    59    99   121    279   
Chile                                    22     2     7     4     13   
China                                     9   201   146   126    473   
Colombia                                 18     2     6    11     19   
Costa Rica                               14     1     1     2      4   
Ivory Coast                              12     0     1     0      1   
Croatia                                   6     6     7    10     23   
Cuba                                     19    72    67    70    209   
Cyprus                                    9     0     1     0      1   
...                                     ...   ...   ...   ...    ...   
Spain                                    22    37    59    35    131   
Sri Lanka                                16     0     2     0      2   
Sudan                                    11     0     1     0      1   
Suriname                                 11     1     0     1      2   
Sweden                                   26   143   164   176    483   
Switzerland                              27    47    73    65    185   
Syria                                    12     1     1     1      3   
Chinese Taipei                           13     2     7    12     21   
Tajikistan                                5     0     1     2      3   
Tanzania                                 12     0     2     0      2   
Thailand                                 15     7     6    11     24   
Togo                                      9     0     0     1      1   
Tonga                                     8     0     1     0      1   
Trinidad and Tobago                      16     2     5    11     18   
Tunisia                                  13     3     3     4     10   
Turkey                                   21    39    25    24     88   
Uganda                                   14     2     3     2      7   
Ukraine                                   5    33    27    55    115   
United Arab Emirates                      8     1     0     0      1   
United States                            26   976   757   666   2399   
Uruguay                                  20     2     2     6     10   
Uzbekistan                                5     5     5    10     20   
Venezuela                                17     2     2     8     12   
Vietnam                                  14     0     2     0      2   
Vir

In [127]:
df

№ Summer  01 !  02 !  03 !  Total  \
Afghanistan                              13     0     0     2      2   
Algeria                                  12     5     2     8     15   
Argentina                                23    18    24    28     70   
Armenia                                   5     1     2     9     12   
Australasia                               2     3     4     5     12   
Australia                                25   139   152   177    468   
Austria                                  26    18    33    35     86   
Azerbaijan                                5     6     5    15     26   
Bahamas                                  15     5     2     5     12   
Bahrain                                   8     0     0     1      1   
Barbados                                 11     0     0     1      1   
Belarus                                   5    12    24    39     75   
Belgium                                  25    37    52    53    142   
Bermuda                                  17     0     0     1      1   
Bohemia                                   3     0     1     3      4   
Botswana                                  9     0     1     0      1   
Brazil                                   21    23    30    55    108   
British West Indies                       1     0     0     2      2   
Bulgaria                                 19    51    85    78    214   
Burundi                                   5     1     0     0      1   
Cameroon                                 13     3     1     1      5   
Canada                                   25    59    99   121    279   
Chile                                    22     2     7     4     13   
China                                     9   201   146   126    473   
Colombia                                 18     2     6    11     19   
Costa Rica                               14     1     1     2      4   
Ivory Coast                              12     0     1     0      1   
Croatia                                   6     6     7    10     23   
Cuba                                     19    72    67    70    209   
Cyprus                                    9     0     1     0      1   
...                                     ...   ...   ...   ...    ...   
Sri Lanka                                16     0     2     0      2   
Sudan                                    11     0     1     0      1   
Suriname                                 11     1     0     1      2   
Sweden                                   26   143   164   176    483   
Switzerland                              27    47    73    65    185   
Syria                                    12     1     1     1      3   
Chinese Taipei                           13     2     7    12     21   
Tajikistan                                5     0     1     2      3   
Tanzania                                 12     0     2     0      2   
Thailand                                 15     7     6    11     24   
Togo                                      9     0     0     1      1   
Tonga                                     8     0     1     0      1   
Trinidad and Tobago                      16     2     5    11     18   
Tunisia                                  13     3     3     4     10   
Turkey                                   21    39    25    24     88   
Uganda                                   14     2     3     2      7   
Ukraine                                   5    33    27    55    115   
United Arab Emirates                      8     1     0     0      1   
United States                            26   976   757   666   2399   
Uruguay                                  20     2     2     6     10   
Uzbekistan                                5     5     5    10     20   
Venezuela                                17     2     2     8     12   
Vietnam                                  14     0     2     0      2   
Virgin Islands                           11     0     1     0      1   
Yug

In [130]:
df

# Summer  Gold  Silver  Bronze  Total  \
Afghanistan                              13     0       0       2      2   
Algeria                                  12     5       2       8     15   
Argentina                                23    18      24      28     70   
Armenia                                   5     1       2       9     12   
Australasia                               2     3       4       5     12   
Australia                                25   139     152     177    468   
Austria                                  26    18      33      35     86   
Azerbaijan                                5     6       5      15     26   
Bahamas                                  15     5       2       5     12   
Bahrain                                   8     0       0       1      1   
Barbados                                 11     0       0       1      1   
Belarus                                   5    12      24      39     75   
Belgium                                  25    37      52      53    142   
Bermuda                                  17     0       0       1      1   
Bohemia                                   3     0       1       3      4   
Botswana                                  9     0       1       0      1   
Brazil                                   21    23      30      55    108   
British West Indies                       1     0       0       2      2   
Bulgaria                                 19    51      85      78    214   
Burundi                                   5     1       0       0      1   
Cameroon                                 13     3       1       1      5   
Canada                                   25    59      99     121    279   
Chile                                    22     2       7       4     13   
China                                     9   201     146     126    473   
Colombia                                 18     2       6      11     19   
Costa Rica                               14     1       1       2      4   
Ivory Coast                              12     0       1       0      1   
Croatia                                   6     6       7      10     23   
Cuba                                     19    72      67      70    209   
Cyprus                                    9     0       1       0      1   
...                                     ...   ...     ...     ...    ...   
Sri Lanka                                16     0       2       0      2   
Sudan                                    11     0       1       0      1   
Suriname                                 11     1       0       1      2   
Sweden                                   26   143     164     176    483   
Switzerland                              27    47      73      65    185   
Syria                                    12     1       1       1      3   
Chinese Taipei                           13     2       7      12     21   
Tajikistan                                5     0       1       2      3   
Tanzania                                 12     0       2       0      2   
Thailand                                 15     7       6      11     24   
Togo                                      9     0       0       1      1   
Tonga                                     8     0       1       0      1   
Trinidad and Tobago                      16     2       5      11     18   
Tunisia                                  13     3       3       4     10   
Turkey                                   21    39      25      24     88   
Uganda                                   14     2       3       2      7   
Ukraine                                   5    33      27      55    115   
United Arab Emirates                      8     1       0       0      1   
United States                            26   976     757     666   2399   
Uruguay                                  20     2       2       6     10   
Uzbekistan                                5     5       5      10     20   
Venezue

In [131]:
df.drop("Totals")

# Summer  Gold  Silver  Bronze  Total  \
Afghanistan                              13     0       0       2      2   
Algeria                                  12     5       2       8     15   
Argentina                                23    18      24      28     70   
Armenia                                   5     1       2       9     12   
Australasia                               2     3       4       5     12   
Australia                                25   139     152     177    468   
Austria                                  26    18      33      35     86   
Azerbaijan                                5     6       5      15     26   
Bahamas                                  15     5       2       5     12   
Bahrain                                   8     0       0       1      1   
Barbados                                 11     0       0       1      1   
Belarus                                   5    12      24      39     75   
Belgium                                  25    37      52      53    142   
Bermuda                                  17     0       0       1      1   
Bohemia                                   3     0       1       3      4   
Botswana                                  9     0       1       0      1   
Brazil                                   21    23      30      55    108   
British West Indies                       1     0       0       2      2   
Bulgaria                                 19    51      85      78    214   
Burundi                                   5     1       0       0      1   
Cameroon                                 13     3       1       1      5   
Canada                                   25    59      99     121    279   
Chile                                    22     2       7       4     13   
China                                     9   201     146     126    473   
Colombia                                 18     2       6      11     19   
Costa Rica                               14     1       1       2      4   
Ivory Coast                              12     0       1       0      1   
Croatia                                   6     6       7      10     23   
Cuba                                     19    72      67      70    209   
Cyprus                                    9     0       1       0      1   
...                                     ...   ...     ...     ...    ...   
Spain                                    22    37      59      35    131   
Sri Lanka                                16     0       2       0      2   
Sudan                                    11     0       1       0      1   
Suriname                                 11     1       0       1      2   
Sweden                                   26   143     164     176    483   
Switzerland                              27    47      73      65    185   
Syria                                    12     1       1       1      3   
Chinese Taipei                           13     2       7      12     21   
Tajikistan                                5     0       1       2      3   
Tanzania                                 12     0       2       0      2   
Thailand                                 15     7       6      11     24   
Togo                                      9     0       0       1      1   
Tonga                                     8     0       1       0      1   
Trinidad and Tobago                      16     2       5      11     18   
Tunisia                                  13     3       3       4     10   
Turkey                                   21    39      25      24     88   
Uganda                                   14     2       3       2      7   
Ukraine                                   5    33      27      55    115   
United Arab Emirates                      8     1       0       0      1   
United States                            26   976     757     666   2399   
Uruguay                                  20     2       2       6     10   
Uzbekis

In [132]:
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan         13     0       0       2      2         0       0   
Algeria             12     5       2       8     15         3       0   
Argentina           23    18      24      28     70        18       0   
Armenia              5     1       2       9     12         6       0   
Australasia          2     3       4       5     12         0       0   

              Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  \
Afghanistan          0         0        0       13       0         0   
Algeria              0         0        0       15       5         2   
Argentina            0         0        0       41      18        24   
Armenia              0         0        0       11       1         2   
Australasia          0         0        0        2       3         4   

              Bronze.2  Combined total  Ids  
Afghanistan          2               2  AFG  
Algeria              8              15  ALG  
Argentina           28              70  ARG  
Armenia              9              12  ARM  
Australasia          5              12  ANZ

In [139]:
df = df.drop("Totals")

In [147]:
argmax?

Object `argmax` not found.


In [149]:
df.where((df["Gold"]>0) &)

# Summer   Gold  Silver  Bronze   Total  \
Afghanistan                             NaN    NaN     NaN     NaN     NaN   
Algeria                                12.0    5.0     2.0     8.0    15.0   
Argentina                              23.0   18.0    24.0    28.0    70.0   
Armenia                                 5.0    1.0     2.0     9.0    12.0   
Australasia                             2.0    3.0     4.0     5.0    12.0   
Australia                              25.0  139.0   152.0   177.0   468.0   
Austria                                26.0   18.0    33.0    35.0    86.0   
Azerbaijan                              5.0    6.0     5.0    15.0    26.0   
Bahamas                                15.0    5.0     2.0     5.0    12.0   
Bahrain                                 NaN    NaN     NaN     NaN     NaN   
Barbados                                NaN    NaN     NaN     NaN     NaN   
Belarus                                 5.0   12.0    24.0    39.0    75.0   
Belgium                                25.0   37.0    52.0    53.0   142.0   
Bermuda                                 NaN    NaN     NaN     NaN     NaN   
Bohemia                                 NaN    NaN     NaN     NaN     NaN   
Botswana                                NaN    NaN     NaN     NaN     NaN   
Brazil                                 21.0   23.0    30.0    55.0   108.0   
British West Indies                     NaN    NaN     NaN     NaN     NaN   
Bulgaria                               19.0   51.0    85.0    78.0   214.0   
Burundi                                 5.0    1.0     0.0     0.0     1.0   
Cameroon                               13.0    3.0     1.0     1.0     5.0   
Canada                                 25.0   59.0    99.0   121.0   279.0   
Chile                                  22.0    2.0     7.0     4.0    13.0   
China                                   9.0  201.0   146.0   126.0   473.0   
Colombia                               18.0    2.0     6.0    11.0    19.0   
Costa Rica                             14.0    1.0     1.0     2.0     4.0   
Ivory Coast                             NaN    NaN     NaN     NaN     NaN   
Croatia                                 6.0    6.0     7.0    10.0    23.0   
Cuba                                   19.0   72.0    67.0    70.0   209.0   
Cyprus                                  NaN    NaN     NaN     NaN     NaN   
...                                     ...    ...     ...     ...     ...   
Spain                                  22.0   37.0    59.0    35.0   131.0   
Sri Lanka                               NaN    NaN     NaN     NaN     NaN   
Sudan                                   NaN    NaN     NaN     NaN     NaN   
Suriname                               11.0    1.0     0.0     1.0     2.0   
Sweden                                 26.0  143.0   164.0   176.0   483.0   
Switzerland                            27.0   47.0    73.0    65.0   185.0   
Syria                                  12.0    1.0     1.0     1.0     3.0   
Chinese Taipei                         13.0    2.0     7.0    12.0    21.0   
Tajikistan                              NaN    NaN     NaN     NaN     NaN   
Tanzania                                NaN    NaN     NaN     NaN     NaN   
Thailand                               15.0    7.0     6.0    11.0    24.0   
Togo                                    NaN    NaN     NaN     NaN     NaN   
Tonga                                   NaN    NaN     NaN     NaN     NaN   
Trinidad and Tobago                    16.0    2.0     5.0    11.0    18.0   
Tunisia                                13.0    3.0     3.0     4.0    10.0   
Turkey                                 21.0   39.0    25.0    24.0    88.0   
Uganda                                 14.0    2.0     3.0     2.0     7.0   
Ukraine                                 5.0   33.0    27.0    55.0   115.0   
United Arab Emirates                    8.0    1.0     0.0     0.0     1.0   
United States                          26.0  976.0   757.

In [150]:
df1 = pd.read_csv("census.csv")

In [154]:
df1["SUMLEV"].unique()

array([40, 50], dtype=int64)

In [155]:
df1

SUMLEV  REGION  DIVISION  STATE  COUNTY     STNAME             CTYNAME  \
0         40       3         6      1       0    Alabama             Alabama   
1         50       3         6      1       1    Alabama      Autauga County   
2         50       3         6      1       3    Alabama      Baldwin County   
3         50       3         6      1       5    Alabama      Barbour County   
4         50       3         6      1       7    Alabama         Bibb County   
5         50       3         6      1       9    Alabama       Blount County   
6         50       3         6      1      11    Alabama      Bullock County   
7         50       3         6      1      13    Alabama       Butler County   
8         50       3         6      1      15    Alabama      Calhoun County   
9         50       3         6      1      17    Alabama     Chambers County   
10        50       3         6      1      19    Alabama     Cherokee County   
11        50       3         6      1      21    Alabama      Chilton County   
12        50       3         6      1      23    Alabama      Choctaw County   
13        50       3         6      1      25    Alabama       Clarke County   
14        50       3         6      1      27    Alabama         Clay County   
15        50       3         6      1      29    Alabama     Cleburne County   
16        50       3         6      1      31    Alabama       Coffee County   
17        50       3         6      1      33    Alabama      Colbert County   
18        50       3         6      1      35    Alabama      Conecuh County   
19        50       3         6      1      37    Alabama        Coosa County   
20        50       3         6      1      39    Alabama    Covington County   
21        50       3         6      1      41    Alabama     Crenshaw County   
22        50       3         6      1      43    Alabama      Cullman County   
23        50       3         6      1      45    Alabama         Dale County   
24        50       3         6      1      47    Alabama       Dallas County   
25        50       3         6      1      49    Alabama       DeKalb County   
26        50       3         6      1      51    Alabama       Elmore County   
27        50       3         6      1      53    Alabama     Escambia County   
28        50       3         6      1      55    Alabama       Etowah County   
29        50       3         6      1      57    Alabama      Fayette County   
...      ...     ...       ...    ...     ...        ...                 ...   
3163      50       2         3     55     131  Wisconsin   Washington County   
3164      50       2         3     55     133  Wisconsin     Waukesha County   
3165      50       2         3     55     135  Wisconsin      Waupaca County   
3166      50       2         3     55     137  Wisconsin     Waushara County   
3167      50       2         3     55     139  Wisconsin    Winnebago County   
3168      50       2         3     55     141  Wisconsin         Wood County   
3169      40       4         8     56       0    Wyoming             Wyoming   
3170      50       4         8     56       1    Wyoming       Albany County   
3171      50       4         8     56       3    Wyoming     Big Horn County   
3172      50       4         8     56       5    Wyoming     Campbell County   
3173      50       4         8     56       7    Wyoming       Carbon County   
3174      50       4         8     56       9    Wyoming     Converse County   
3175      50       4         8     56      11    Wyoming        Crook County   
3176      50       4         8     56      13    Wyoming      Fremont County   
3177      50       4         8     56      15    Wyoming       Goshen County   
3178      50       4         8     56      17    Wyoming  Hot Springs County   
3179      50       4         8     56      19    Wyoming      Johnson County   
3180      50       4         8     56      21    Wyoming      Laramie County   
3181  

In [156]:
df1["STNAME"].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [176]:
df1["STNAME"].value_counts().argmax()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  """Entry point for launching an IPython kernel.


'Texas'

In [177]:
df1.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  ...  RDOMESTICMIG2011  \
0        4779736            4780127          4785161  ...          0.002295   
1          54571              54571            54660  ...          7.242091   
2         182265             182265           183193  ...         14.832960   
3          27457              27457            27341  ...         -4.728132   
4          22915              22919            22861  ...         -5.527043   

   RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  RDOMESTICMIG2015  \
0         -0.193196          0.381066          0.582002         -0.467369   
1         -2.915927         -3.012349          2.265971         -2.530799   
2         17.647293         21.845705         19.243287         17.197872   
3         -2.500690         -7.056824         -3.904217        -10.543299   
4         -5.068871         -6.201001         -0.177537          0.177258   

   RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015  
0     1.030015     0.826644     1.383282     1.724718     0.712594  
1     7.606016    -2.626146    -2.722002     2.592270    -2.187333  
2    15.844176    18.559627    22.727626    20.317142    18.293499  
3    -4.874741    -2.758113    -7.167664    -3.978583   -10.543299  
4    -5.088389    -4.363636    -5.403729     0.754533     1.107861  

[5 rows x 100 columns]

In [197]:
a = df1[["STNAME","CENSUS2010POP","CTYNAME"]]

In [198]:
import numpy as np

In [199]:
a

STNAME  CENSUS2010POP             CTYNAME
0       Alabama        4779736             Alabama
1       Alabama          54571      Autauga County
2       Alabama         182265      Baldwin County
3       Alabama          27457      Barbour County
4       Alabama          22915         Bibb County
5       Alabama          57322       Blount County
6       Alabama          10914      Bullock County
7       Alabama          20947       Butler County
8       Alabama         118572      Calhoun County
9       Alabama          34215     Chambers County
10      Alabama          25989     Cherokee County
11      Alabama          43643      Chilton County
12      Alabama          13859      Choctaw County
13      Alabama          25833       Clarke County
14      Alabama          13932         Clay County
15      Alabama          14972     Cleburne County
16      Alabama          49948       Coffee County
17      Alabama          54428      Colbert County
18      Alabama          13228      Conecuh County
19      Alabama          11539        Coosa County
20      Alabama          37765    Covington County
21      Alabama          13906     Crenshaw County
22      Alabama          80406      Cullman County
23      Alabama          50251         Dale County
24      Alabama          43820       Dallas County
25      Alabama          71109       DeKalb County
26      Alabama          79303       Elmore County
27      Alabama          38319     Escambia County
28      Alabama         104430       Etowah County
29      Alabama          17241      Fayette County
...         ...            ...                 ...
3163  Wisconsin         131887   Washington County
3164  Wisconsin         389891     Waukesha County
3165  Wisconsin          52410      Waupaca County
3166  Wisconsin          24496     Waushara County
3167  Wisconsin         166994    Winnebago County
3168  Wisconsin          74749         Wood County
3169    Wyoming         563626             Wyoming
3170    Wyoming          36299       Albany County
3171    Wyoming          11668     Big Horn County
3172    Wyoming          46133     Campbell County
3173    Wyoming          15885       Carbon County
3174    Wyoming          13833     Converse County
3175    Wyoming           7083        Crook County
3176    Wyoming          40123      Fremont County
3177    Wyoming          13249       Goshen County
3178    Wyoming           4812  Hot Springs County
3179    Wyoming           8569      Johnson County
3180    Wyoming          91738      Laramie County
3181    Wyoming          18106      Lincoln County
3182    Wyoming          75450      Natrona County
3183    Wyoming           2484     Niobrara County
3184    Wyoming          28205         Park County
3185    Wyoming           8667       Platte County
3186    Wyoming          29116     Sheridan County
3187    Wyoming          10247     Sublette County
3188    Wyoming          43806   Sweetwater County
3189    Wyoming          21294        Teton County
3190    Wyoming          21118        Uinta County
3191    Wyoming           8533     Washakie County
3192    Wyoming           7208       Weston County

[3193 rows x 3 columns]

In [223]:
mask=df1['SUMLEV']==50
mask

0       False
1        True
2        True
3        True
4        True
5        True
6        True
7        True
8        True
9        True
10       True
11       True
12       True
13       True
14       True
15       True
16       True
17       True
18       True
19       True
20       True
21       True
22       True
23       True
24       True
25       True
26       True
27       True
28       True
29       True
        ...  
3163     True
3164     True
3165     True
3166     True
3167     True
3168     True
3169    False
3170     True
3171     True
3172     True
3173     True
3174     True
3175     True
3176     True
3177     True
3178     True
3179     True
3180     True
3181     True
3182     True
3183     True
3184     True
3185     True
3186     True
3187     True
3188     True
3189     True
3190     True
3191     True
3192     True
Name: SUMLEV, Length: 3193, dtype: bool

In [262]:
a = df1[["STNAME","CTYNAME","CENSUS2010POP"]]
a.index = a["STNAME"]

In [265]:
a.head()


STNAME         CTYNAME  CENSUS2010POP
STNAME                                         
Alabama  Alabama         Alabama        4779736
Alabama  Alabama  Autauga County          54571
Alabama  Alabama  Baldwin County         182265
Alabama  Alabama  Barbour County          27457
Alabama  Alabama     Bibb County          22915

In [269]:
a["CENSUS2010POP"].max()

37253956

In [320]:
b = pd.read_csv("census.csv")


In [347]:
for i in b.groupby(["STNAME"]):
    a=b[["CTYNAME","CENSUS2010POP"]
        

AttributeError: 'DataFrame' object has no attribute 'sort'

In [341]:
a

CTYNAME  CENSUS2010POP
0                Alabama        4779736
1         Autauga County          54571
2         Baldwin County         182265
3         Barbour County          27457
4            Bibb County          22915
5          Blount County          57322
6         Bullock County          10914
7          Butler County          20947
8         Calhoun County         118572
9        Chambers County          34215
10       Cherokee County          25989
11        Chilton County          43643
12        Choctaw County          13859
13         Clarke County          25833
14           Clay County          13932
15       Cleburne County          14972
16         Coffee County          49948
17        Colbert County          54428
18        Conecuh County          13228
19          Coosa County          11539
20      Covington County          37765
21       Crenshaw County          13906
22        Cullman County          80406
23           Dale County          50251
24         Dallas County          43820
25         DeKalb County          71109
26         Elmore County          79303
27       Escambia County          38319
28         Etowah County         104430
29        Fayette County          17241
...                  ...            ...
3163   Washington County         131887
3164     Waukesha County         389891
3165      Waupaca County          52410
3166     Waushara County          24496
3167    Winnebago County         166994
3168         Wood County          74749
3169             Wyoming         563626
3170       Albany County          36299
3171     Big Horn County          11668
3172     Campbell County          46133
3173       Carbon County          15885
3174     Converse County          13833
3175        Crook County           7083
3176      Fremont County          40123
3177       Goshen County          13249
3178  Hot Springs County           4812
3179      Johnson County           8569
3180      Laramie County          91738
3181      Lincoln County          18106
3182      Natrona County          75450
3183     Niobrara County           2484
3184         Park County          28205
3185       Platte County           8667
3186     Sheridan County          29116
3187     Sublette County          10247
3188   Sweetwater County          43806
3189        Teton County          21294
3190        Uinta County          21118
3191     Washakie County           8533
3192       Weston County           7208

[3193 rows x 2 columns]